name:                FootGame
version:             0.1.0.0
github:              "bartoszw/FootGame"
license:             BSD3
author:              "Bartosz Wójcik"
maintainer:          "bartoszmwojcik@gmail.com"
copyright:           "Bartosz Wójcik"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bartoszw/FootGame#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- gloss
- hashmap >= 1.3.3
- array
- Spock >= 0.14

library:
  source-dirs: src

executables:
  FootGame:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FootGame

tests:
  FootGame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FootGame
